spring:
 datasource:
   url: jdbc:mysql://localhost:3306/nw?useSSL=true
   username: root
   password: root
 application:
    name: microservice-provider-user
   
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration-properties:
   #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
   map-underscore-to-camel-case: true
